$(function(){
	$('.bxslider').bxSlider({
		auto:true,
		speed:500,
		pause:5000,
		mode:'horizontal'
	});
	$("#leftBanner").click(function(){
		location.href="../cafe&restaurant/restaurant.jsp";
	});
	$("#rightBanner").click(function(){
		location.href="../cafe&restaurant/cafe.jsp";
	});
});